name: CI
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anndutova/go-course-tests:v1.0.0
    steps:
      - uses: actions/checkout@v4

      - name: Move files
        run: mv KthLargest/main.go /test/file.go

      - name: Run test
        working-directory: /test
        run: go test
