name: CI
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anndutova/go-course-tests:latest
    steps:
      - uses: actions/checkout@v3

      - name: Print structure
        run: ls -R

      - name: move file to test
        run: mv /KthLargest/main.go /test/file.go

      - name: Run test
        working-directory: /test
        run: go test
