name: CI
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anndutova/go-course-tests:latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test
        working-directory: /KthLargest
        run: go test
