name: CI
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anndutova/go-course-tests:v1.0.0
    steps:
      - uses: actions/checkout@v4

      - name: Get directory
        run: ls

      - name: Move file
        run: mv /KthLargest/*.go /test

      - name: Run test
        working-directory: /KthLargest
        run: go test
